repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
          \./idea|
          \./vscode|
          .coverage
      )$
  - id: trailing-whitespace
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.11
  hooks:
    - id: ruff
      args: [ "--line-length=120", "--target-version=py311" ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy
      args: ["--check-untyped-defs", "--ignore-missing-imports"]
      exclude: ^tests/
-   repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
    - id: black
      language_version: python3.8
