site_name: FastAPI Response Schema
repo_url: https://github.com/acwazz/fastapi-responseschema
repo_name: fastapi-responseschema

theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/meteor
    repo: fontawesome/brands/github
  font:
    text: Fira Sans
    code: Fira Code
  palette:
    # Toggle light mode
    - scheme: default
      primary: orange
      accent: teal
      toggle:
        icon: fontawesome/solid/moon
        name: Dark mode
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: fontawesome/regular/lightbulb
        name: Light mode

plugins:
  - search:
      lang: en
  - tags

nav:
    - Guide: 
      - Prelude: 'index.md'
      - Schemas: 'guide/schemas.md'
      - Routing: 'guide/api_routes.md'
      - Utilities: 'guide/utilities.md'
      - Pagination: 'guide/pagination_integration.md'
    - API: 
      - Interfaces: 'api/interfaces.md'
      - Exceptions: 'api/exceptions.md'
      - Routing: 'api/routing.md'
      - Helpers: 'api/helpers.md'
    - Contibuting: 'contributing.md'