name: Build and deploy docs
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Testing'
        required: false
        type: boolean
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: { python-version: "3.8" }

    - name: Install dependencies
      run: |
        pip install -U poetry
        poetry install
    - name: Build documentation
      run: |
        poetry run novella -d docs
    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
