name: Type Check
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
  push:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/mypy-check@master
        with:
          path: '.'
